name: Test Secure Action

on:
  workflow_dispatch:
    inputs:
      input_directory:
        description: 'Directory containing API source code (relative to workspace)'
        required: false
        default: "."
        type: string        

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: CodeGlide MCP Generator
      uses: CodeGlide/codeglide-mcpgen@v1.0.0
      with:
        input_directory: ${{ inputs.input_directory }}
